CREATE FUNCTION HITUNG_JUMLAH_PERJALANAN(
    ITINERARY_ID INT
) RETURNS INT DETERMINISTIC
BEGIN
    DECLARE JUMLAH_KEGIATAN INT;
    SELECT
        COUNT(*) INTO JUMLAH_KEGIATAN
    FROM
        ACTIVITY
    WHERE
        ITINERARY_ID = ITINERARY_ID;
    RETURN JUMLAH_KEGIATAN;
END;