CREATE PROCEDURE TAMBAH_KEGIATAN(
    IN ITINERARY_ID INT,
    IN ACTIVITY_NAME VARCHAR(255),
    IN ACTIVITY_DATE DATE,
    IN TIME_START TIME,
    IN LOCATION_ID INT
)
BEGIN
    INSERT INTO ACTIVITY (
        ITINERARY_ID,
        ACTIVITY_NAME,
        ACTIVITY_DATE,
        TIME_START,
        LOCATION_ID
    ) VALUES (
        ITINERARY_ID,
        ACTIVITY_NAME,
        ACTIVITY_DATE,
        TIME_START,
        LOCATION_ID
    );
END;