CREATE TRIGGER CHECK_TANGGAL_SELESAI BEFORE
    INSERT ON ITINERARYPLANNER FOR EACH ROW
BEGIN
    IF NEW.END_DATE < NEW.START_DATE THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Tanggal Selesai tidak boleh kurang dari Tanggal Mulai';
    END IF;
END;

CREATE TRIGGER UPDATE_TANGGAL_CHECKOUT AFTER INSERT ON ACCOMMODATION FOR EACH ROW BEGIN UPDATE ACCOMMODATION SET CHECKOUT_DATE = DATE_ADD(
    NEW.CHECKIN_DATE,
    INTERVAL 1 DAY
) WHERE ITINERARY_ID = NEW.ITINERARY_ID;
END;