-- Active: 1718620152358@@127.0.0.1@3306@itineraryplanner
CREATE VIEW VIEW_RENCANA_PERJALANAN AS
    SELECT
        U.USERNAME       AS NAMA_PENGGUNA,
        I.ITINERARY_NAME AS NAMA_PERJALANAN,
        I.START_DATE     AS TANGGAL_MULAI,
        I.END_DATE       AS TANGGAL_SELESAI
    FROM
        USER             U
        JOIN ITINERARYPLANNER I
        ON U.USER_ID = I.USER_ID;

CREATE VIEW VIEW_DETAIL_KEGIATAN AS
    SELECT
        I.ITINERARY_NAME AS NAMA_PERJALANAN,
        A.ACTIVITY_NAME  AS NAMA_KEGIATAN,
        A.ACTIVITY_DATE  AS TANGGAL_KEGIATAN,
        A.TIME_START     AS WAKTU_MULAI
    FROM
        ITINERARYPLANNER I
        JOIN ACTIVITY A
        ON I.ITINERARY_ID = A.ITINERARY_ID
        JOIN LOCATION L
        ON A.LOCATION_ID = L.LOCATION_ID;